---
- name: Call AO Webhook
  hosts: localhost
  gather_facts: false

  vars:
    ao_webhook_base_url: http://automation-orchestrator-ui.automation-orchestrator.svc.cluster.local

  tasks:

    - name: Obtain OAuth token
      ansible.builtin.uri:
        url: "{{ ao_webhook_base_url }}/api/v1/auth/token"
        method: POST
        body_format: form-urlencoded
        validate_certs: false
        body:
          grant_type: client_credentials
          client_id: "{{ ao_webhook_client_id }}"
          client_secret: "{{ ao_webhook_client_secret }}"
        status_code: 200
      register: token_response
      no_log: true

    - name: Post event payload to Event-Driven Ansible trigger endpoint
      ansible.builtin.uri:
        url: "{{ ao_webhook_base_url }}/api/v1/webhooks/eda/{{ ao_webhook_path }}"
        method: POST
        body_format: json
        validate_certs: false
        headers:
          Authorization: "Bearer {{ token_response.json.access_token }}"
          Content-Type: application/json
        body: >-
          {{
            {
              'issue_number': issue_number | default(forego_issue_number | default(None)),
              'alert_payload': alert_payload | default(None),
              'check_audit_service_issue': check_audit_service_issue | default(None),
            } | dict2items | rejectattr('value', 'none') | items2dict
          }}
        status_code: 202
      register: webhook_response
      no_log: true

    - name: Display execution ID
      ansible.builtin.debug:
        msg: "Workflow execution started: {{ webhook_response.json.execution_id }}"

    - name: Publish the workflow execution as a job artifact
      ansible.builtin.set_stats:
        data:
          ao_execution_id: "{{ webhook_response.json.execution_id }}"
